input_functions = [
    {
        "name": "get_vehicle_data",
        "description": "Use this function to get vehicle details from database to answer user questions.\
            Remember! Try to think as much as possible. \
            You must not call this function when the uer's question is ambitious or it's not appropriate for this function",
        "parameters": {
            "type": "object",
            "properties": {
                "limit_count": {
                    "type": "number",
                    "description": "The limit count that the customer wants. Default value is 3, and can be 10 at most.",
                },
                "listing_stock": {
                    "type": "string",
                    "description": "A unique identifier or stock number associated with the vehicle listing. This identifier is used for tracking and referencing specific listings(i.e. 'A230402A', '01-MAZDA-MPV', etc).",
                },
                "price_description": {
                    "type": "string",
                    "enum": [
                        "range",
                        "the most expensive",
                        "the cheapest",
                    ],
                    "description": "The most appropriate description for the price, (i.e. 'the cheapeast', 'the most expensive', 'range : (100-300)', etc.)",
                },
                "listing_min_price": {
                    "type": "number",
                    "description": "The lower bound price for the car",
                },
                "listing_max_price": {
                    "type": "number",
                    "description": "The upper bound price for the car",
                },
                "listing_type": {
                    "type": "string",
                    "enum": ["Used", "New", "Certified"],
                    "description": "The listing type of the vehicle (i.e. 'Used', 'New', or 'Certified', etc.)",
                },
                "listing_mileage": {
                    "type": "number",
                    "description": "The number of miles that the vehicle has been driven, indicating its usage and wear.",
                },
                "vehicle_min_year": {
                    "type": "number",
                    "description": "The manufacturing lower bound year of the vehicle, specifying its production year. For example, if the user wants 2018 product, it's 2018. And over 2018, it's 2018",
                },
                "vehicle_max_year": {
                    "type": "number",
                    "description": "The manufacturing upper bound year of the vehicle, specifying its production year. For example, if the user wants 2020 product, it's 2020. And before 2020, it's 2019",
                },
                "vehicle_make": {
                    "type": "string",
                    "description": "The manufacturer or brand of the vehicle, the company that produced it (i.e. 'Hyundai','Toyota', etc. ).",
                },
                "vehicle_model": {
                    "type": "string",
                    "description": "The specific model name of the vehicle, providing further details about its series or edition (i.e. 'Kona', 'Altima', 'Camry', etc.).",
                },
                "vehicle_trim": {
                    "type": "string",
                    "description": "The trim level or package of the car, highlighting any additional features or options included (i.e. 'Essence', 'M440i xDrive', 'Sport', etc.).",
                },
                "vehicle_style": {
                    "type": "string",
                    "description": "The style or body type of the vehicle, describing its physical appearance and design, such as 'coupe', 'sedan', 'convertible', etc.",
                },
                "vehicle_color_exterior": {
                    "type": "string",
                    "description": "The color of the vehicle's exterior, such as 'black', 'red', 'white', 'silver', 'Satin Steel Metallic', etc",
                },
                "vehicle_color_interior": {
                    "type": "string",
                    "description": "The color of the vehicle's interior, such as 'black', 'Charcoal Leather', 'shadow gray', 'silver', 'gray', etc",
                },
                "va_seller_name": {
                    "type": "string",
                    "description": "The name of the seller or dealership offering the vehicle for sale, such as 'Tasca Subaru Yonkers.'",
                },
                "va_seller_websites": {
                    "type": "string",
                    "description": "The website URL of the seller or dealership where the vehicle is listed for sale, such as 'https://www.tascasubaruyonkers.com.'",
                },
                "va_seller_phones": {
                    "type": "string",
                    "description": "The contact phone number associated with the seller or dealership offering the vehicle (i.e. 914-377-8100).",
                },
                "va_seller_type": {
                    "type": "string",
                    "enum": ["Franchise", "Independent"],
                    "description": "Type or category of the seller or dealership (i.e. 'Franchise', 'Independent').",
                },
                "va_seller_address": {
                    "type": "string",
                    "description": "Address of the seller.",
                },
                "va_seller_city": {
                    "type": "string",
                    "description": "City where the seller is located.",
                },
                "va_seller_state": {
                    "type": "string",
                    "description": "State where the seller is located.",
                },
                "va_seller_zip": {
                    "type": "string",
                    "description": "ZIP code of the seller's location.",
                },
                "va_seller_county": {
                    "type": "string",
                    "description": "County where the seller is located.",
                },
                "va_seller_country": {
                    "type": "string",
                    "description": "Country where the seller is located.",
                },
                "va_seller_makes": {
                    "type": "string",
                    "description": "Vehicle makes associated with the seller. (i.e. 'Honda', 'Chrysler,Dodge,Jeep,Ram', etc)",
                },
                "va_seller_inventory_count_total": {
                    "type": "integer",
                    "description": "Total count of vehicles in the seller's inventory.",
                },
                "va_seller_inventory_count_new": {
                    "type": "integer",
                    "description": "Count of new vehicles in the seller's inventory.",
                },
                "va_seller_inventory_count_used": {
                    "type": "integer",
                    "description": "Count of used vehicles in the seller's inventory.",
                },
                "vdp_url": {
                    "type": "string",
                    "description": "URL of the Vehicle Detail Page for the listing.",
                },
                "ymmt_id": {
                    "type": "string",
                    "description": "Identifier for Year, Make, Model, and Trim (YMMT) information. (i.e. 2016_nissan_rogue_sl, 2001_mazda_mpv_lx, etc.)",
                },
                "listing_features": {
                    "type": "string",
                    "description": "Features of the vehicle listed. For example 'Leather Seats, Sunroof/Moonroof, Navigation System, Alloy Wheels, Bluetooth, Backup Camera, Remote Start, Blind Spot Monitoring, Premium Package, Heated Seats'",
                },
                "vehicle_title": {
                    "type": "string",
                    "description": "Title of the vehicle listing. For example, '2016 Nissan Rogue', '2017 Ford F-150 Limited SuperCrew 4WD', etc.",
                },
                "vehicle_subtitle": {
                    "type": "string",
                    "description": "Subtitle of the vehicle listing. (i.e. 'AWD 4dr SL', '2024 Toyota Grand Highlander XLE', etc.)",
                },
                "vehicle_type": {
                    "type": "string",
                    "description": "Type of vehicle (e.g., SUV, Sedan).",
                },
                "vehicle_truck_cab_style": {
                    "type": "string",
                    "description": "Truck cab style for pickup trucks. (e.g. 'Crew Cab', etc.)",
                },
                "vehicle_truck_bed_style": {
                    "type": "string",
                    "description": "Truck bed style for pickup trucks. (e.g. 'Long Bed', 'Short Bed', etc.)",
                },
                "vehicle_engine": {
                    "type": "string",
                    "description": "Description of the vehicle's engine. (i.e. '2.5L I4 16V PDI DOHC', '5.3L V8 16V GDI OHV', etc.)",
                },
                "vehicle_engine_size": {
                    "type": "number",
                    "description": "Size of the vehicle's engine. (i.e. '6.2', '2.0', etc.)",
                },
                "vehicle_engine_cylinders": {
                    "type": "integer",
                    "description": "Number of cylinders in the engine. (i.e. 'I4', '6', etc.)",
                },
                "vehicle_transmission": {
                    "type": "string",
                    "description": "Description of the vehicle's transmission. (i.e. '1-Speed Automatic', 'Automatic CVT', etc.)",
                },
                "vehicle_transmission_type": {
                    "type": "string",
                    "description": "Type of transmission (e.g., Automatic, Manual).",
                },
                "vehicle_transmission_speed": {
                    "type": "integer",
                    "description": "Number of speeds in the transmission.",
                },
                "vehicle_drivetrain": {
                    "type": "string",
                    "description": "Type of drivetrain (e.g., All-wheel Drive, Front-wheel Drive).",
                },
                "vehicle_doors": {
                    "type": "integer",
                    "description": "Number of doors on the vehicle.",
                },
                "vehicle_fuel_type": {
                    "type": "string",
                    "description": "Type of fuel the vehicle uses. (e.g., 'Gasoline', 'Hybrid')",
                },
                "vehicle_fuel_efficiency": {
                    "type": "string",
                    "description": "Overall fuel efficiency of the vehicle. (e.g., '18.25 MPG', '33.25 MPG')",
                },
                "vehicle_fuel_efficiency_highway": {
                    "type": "string",
                    "description": "Fuel efficiency on the highway.(i.e., '39 MPG', '23 MPG')",
                },
                "vehicle_fuel_efficiency_city": {
                    "type": "string",
                    "description": "Fuel efficiency in the city. (i.e., '35 MPG', '28 MPG')",
                },
                "vehicle_history_description": {
                    "type": "string",
                    "description": "Description of the vehicle's history. (e.g. 'Rental Use')",
                },
                "vehicle_history_critical_count": {
                    "type": "integer",
                    "description": "Count of critical events in the vehicle's history.",
                },
                "vehicle_history_accident_count": {
                    "type": "integer",
                    "description": "Count of accidents in the vehicle's history.",
                },
                "vehicle_history_theft_count": {
                    "type": "integer",
                    "description": "Count of theft incidents in the vehicle's history.",
                },
                "vehicle_history_salvage_count": {
                    "type": "integer",
                    "description": "Count of salvage incidents in the vehicle's history.",
                },
                "vehicle_history_service_count": {
                    "type": "integer",
                    "description": "Count of service events in the vehicle's history.",
                },
                "vehicle_history_owner_count": {
                    "type": "integer",
                    "description": "Count of previous owners in the vehicle's history.",
                },
                "portal_urls": {
                    "type": "string",
                    "description": "URL of the vehicle listing on various portals. (i.e. 'https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=674780315','https://www.carfax.com/vehicle/5N1AT2MV9GC810504',https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action#listing=351461535,'https://www.cars.com/vehicledetail/d4da7600-e9e3-47f0-8462-bd1ad41ef3d0/','https://www.edmunds.com/nissan/rogue/2016/vin/5N1AT2MV9GC810504/')",
                },
                # "portal_deal_ratings": {
                #     "type": "object",
                #     "properties": {
                #         "portal_name": {
                #             "type": "string",
                #             "description": "Name of the portal.",
                #         },
                #         "rating": {
                #             "type": "number",
                #             "description": "Rating of the deal on the portal.",
                #         },
                #     },
                #     "description": "Ratings of the deal on different portals. (i.e. autotrader.com:GOOD,edmunds.com:GOOD,cars.com:GREAT,cargurus.com:GOOD)",
                # },
                # "portal_days_online": {
                #     "type": "object",
                #     "properties": {
                #         "portal_name": {
                #             "type": "string",
                #             "description": "Name of the portal.",
                #         },
                #         "days_online": {
                #             "type": "integer",
                #             "description": "Number of days the listing has been online on the portal.",
                #         },
                #     },
                #     "description": "Number of days the listing has been online on portals. (i.e. edmunds.com:3,cargurus.com:4)",
                # },
                # "portal_prices": {
                #     "type": "object",
                #     "properties": {
                #         "portal_name": {
                #             "type": "string",
                #             "description": "Name of the portal.",
                #         },
                #         "price": {
                #             "type": "number",
                #             "description": "Price of the vehicle listing on the portal.",
                #         },
                #     },
                #     "description": "Prices of the vehicle listing on different portals. (e.g. autotrader.com:17500,edmunds.com:17500,cars.com:17500,cargurus.com:17500,carfax.com:17500)",
                # },
                # # "portal_titles": {
                # #     "type": "object",
                # #     "properties": {
                # #         "portal_name": {
                # #             "type": "string",
                # #             "description": "Name of the portal.",
                # #         },
                # #         "title": {
                # #             "type": "string",
                # #             "description": "Title of the listing on the portal.",
                # #         },
                # #     },
                # #     "description": "Titles of the listing on different portals. (e.g. autotrader.com:Used 2016 Nissan Rogue SL w/ SL Premium Package,edmunds.com:2016 Nissan Rogue,cars.com:2016 Nissan Rogue SL,cargurus.com:2016 Nissan Rogue SL AWD,carfax.com:2016 Nissan Rogue SL)",
                # # },
                # "vdp_url_last_crawled": {
                #     "type": "string",
                #     "description": "Timestamp of the last crawl of the Vehicle Detail Page URL. (e.g. 1694923200, 1695009600)",
                # },
                # "vehicle_history_report_urls": {
                #     "type": "array",
                #     "items": {"type": "string"},
                #     "description": "URLs for vehicle history reports. (e.g. https://www.carfax.com/VehicleHistory/ar20/l_b56v5eemSd-D4nzldIGP0v1s7OutrxNuV5IeDRfGD19eEoMXu4WsCpqBzRPk-ckFHs2DfAVK8HPT3neJ4XepeHQ3pgaV-ZziQ)",
                # },
                # "va_seller_portal_websites": {
                #     "type": "array",
                #     "items": {"type": "string"},
                #     "description": "Websites associated with the seller's portal. (e.g. cargurus.com:circlehyundai.com;cars.com:sawyerlyonsbuickgmc.com;autotrader.com:circleauto.com;edmunds.com:sawyerlyonsbuickgmc.com)",
                # },
                # "va_seller_portal_urls": {
                #     "type": "object",
                #     "properties": {
                #         "portal_name": {
                #             "type": "string",
                #             "description": "Name of the portal.",
                #         },
                #         "url": {
                #             "type": "string",
                #             "description": "URL for the seller's portal on the platform.",
                #         },
                #     },
                #     "description": "URLs for the seller's portal on various platforms.(e.g. https://www.autotrader.com/car-dealers/vienna-va-22182/627565,https://www.cargurus.com/Cars/m-Koons-Tysons-Toyota-sp54851,https://www.cars.com/dealers/2451,https://www.edmunds.com/dealerships/all/virginia/vienna/KoonsTysonsToyota_18221)",
                # },
            },
            "required": ["price_description"],
        },
    }
]
first_field_label_descriptions = {
    "vid_vin": "Vehicle Identification Number (VIN) that uniquely identifies the vehicle",
    "date_min": "Start date of the vehicle listing",
    "date_max": "End date of the vehicle listing",
    "days_seen": "Total number of days the vehicle listing has been active",
    "listing_stock": "Stock identifier for the vehicle listing",
    "listing_price": "Price of the vehicle listing",
    "listing_type": "Type of listing (Used/New/Certified)",
    "listing_mileage": "Number of miles the vehicle has been driven",
    "vehicle_year": "Manufacturing year of the vehicle",
    "vehicle_make": "Manufacturer company of the vehicle",
    "vehicle_model": "Model of the vehicle",
    "vehicle_trim": "Trim level of the vehicle",
    "vehicle_style": "Style or body type of the vehicle",
    "vehicle_color_exterior": "Exterior color of the vehicle",
    "vehicle_color_interior": "Interior color of the vehicle",
    "va_seller_id": "Seller's unique identifier",
    "va_seller_name": "Name of the seller",
    "va_seller_address": "Address of the seller",
    "va_seller_city": "City where the seller is located",
    "va_seller_state": "State where the seller is located",
    "va_seller_zip": "ZIP code of the seller's location",
    "va_seller_county": "County where the seller is located",
    "va_seller_country": "Country where the seller is located",
    "va_seller_websites": "Websites associated with the seller",
    "va_seller_phones": "Contact phone numbers for the seller",
    "va_seller_type": "Type of seller (e.g., Franchise, Independent)",
    "va_seller_makes": "Vehicle makes associated with the seller",
    "va_seller_inventory_count_total": "Total count of vehicles in the seller's inventory",
    "va_seller_inventory_count_new": "Count of new vehicles in the seller's inventory",
    "va_seller_inventory_count_used": "Count of used vehicles in the seller's inventory",
    "vdp_url": "URL of the Vehicle Detail Page for the listing",
    "ymmt_id": "Identifier for Year, Make, Model, and Trim (YMMT) information",
    # "listing_description": "Detailed description of the vehicle listing",
    "listing_features": "Features of the vehicle listed",
    "vehicle_title": "Title of the vehicle listing",
    "vehicle_subtitle": "Subtitle of the vehicle listing",
    "vehicle_type": "Type of vehicle (e.g., SUV, Sedan)",
    "vehicle_truck_cab_style": "Truck cab style for pickup trucks",
    "vehicle_truck_bed_style": "Truck bed style for pickup trucks",
    "vehicle_engine": "Description of the vehicle's engine",
    "vehicle_engine_size": "Size of the vehicle's engine",
    "vehicle_engine_cylinders": "Number of cylinders in the engine",
    "vehicle_transmission": "Description of the vehicle's transmission",
    "vehicle_transmission_type": "Type of transmission (e.g., Automatic, Manual)",
    "vehicle_transmission_speed": "Number of speeds in the transmission",
    "vehicle_drivetrain": "Type of drivetrain (e.g., All-wheel Drive, Front-wheel Drive)",
    "vehicle_doors": "Number of doors on the vehicle",
    "vehicle_fuel_type": "Type of fuel the vehicle uses",
    "vehicle_fuel_efficiency": "Overall fuel efficiency of the vehicle",
    "vehicle_fuel_efficiency_highway": "Fuel efficiency on the highway",
    "vehicle_fuel_efficiency_city": "Fuel efficiency in the city",
    "vehicle_history_description": "Description of the vehicle's history",
    "vehicle_history_critical_count": "Count of critical events in the vehicle's history",
    "vehicle_history_accident_count": "Count of accidents in the vehicle's history",
    "vehicle_history_theft_count": "Count of theft incidents in the vehicle's history",
    "vehicle_history_salvage_count": "Count of salvage incidents in the vehicle's history",
    "vehicle_history_service_count": "Count of service events in the vehicle's history",
    "vehicle_history_owner_count": "Count of previous owners in the vehicle's history",
    "portal_urls": "URLs of the vehicle listing on various portals",
    "portal_deal_ratings": "Ratings of the deal on different portals",
    "portal_days_online": "Number of days the listing has been online on portals",
    "portal_prices": "Prices of the vehicle listing on different portals",
    "portal_titles": "Titles of the listing on different portals",
    "vdp_url_last_crawled": "Timestamp of the last crawl of the Vehicle Detail Page URL",
    "vehicle_history_report_urls": "URLs for vehicle history reports",
    "va_seller_portal_websites": "Websites associated with the seller's portal",
    "va_seller_portal_urls": "URLs for the seller's portal on various platforms",
}

first_table_query_assist = {
    "between": [(("vehicle_min_year", "vehicle_max_year"), "vehicle_year", "BETWEEN")],
    "same": [
        ("listing_stock", "ILIKE"),
        ("listing_type", "ILIKE"),
        ("listing_mileage", "ILIKE"),
        ("vehicle_make", "ILIKE"),
        ("vehicle_model", "ILIKE"),
        ("vehicle_trim", "ILIKE"),
        ("vehicle_style", "ILIKE"),
        ("vehicle_color_exterior", "ILIKE"),
        ("vehicle_color_interior", "ILIKE"),
        ("va_seller_name", "ILIKE"),
        ("va_seller_websites", "ILIKE"),
        ("va_seller_phones", "ILIKE"),
        ("va_seller_type", "ILIKE"),
        ("va_seller_address", "ILIKE"),
        ("va_seller_city", "ILIKE"),
        ("va_seller_state", "ILIKE"),
        ("va_seller_zip", "ILIKE"),
        ("va_seller_county", "ILIKE"),
        ("va_seller_country", "ILIKE"),
        ("va_seller_makes", "ILIKE"),
        ("va_seller_inventory_count_total", "="),
        ("va_seller_inventory_count_new", "="),
        ("va_seller_inventory_count_used", "="),
        ("vdp_url", "ILIKE"),
        ("ymmt_id", "ILIKE"),
        ("listing_features", "ILIKE"),
        ("vehicle_title", "ILIKE"),
        ("vehicle_subtitle", "ILIKE"),
        ("vehicle_type", "ILIKE"),
        ("vehicle_truck_cab_style", "ILIKE"),
        ("vehicle_truck_bed_style", "ILIKE"),
        ("vehicle_engine", "ILIKE"),
        ("vehicle_engine_size", "="),
        ("vehicle_engine_cylinders", "="),
        ("vehicle_transmission", "ILIKE"),
        ("vehicle_transmission_type", "ILIKE"),
        ("vehicle_transmission_speed", "="),
        ("vehicle_drivetrain", "ILIKE"),
        ("vehicle_doors", "="),
        ("vehicle_fuel_type", "ILIKE"),
        ("vehicle_fuel_efficiency", "ILIKE"),
        ("vehicle_fuel_efficiency_highway", "ILIKE"),
        ("vehicle_fuel_efficiency_city", "ILIKE"),
        ("vehicle_history_description", "ILIKE"),
        ("vehicle_history_critical_count", "="),
        ("vehicle_history_accident_count", "="),
        ("vehicle_history_theft_count", "="),
        ("vehicle_history_salvage_count", "="),
        ("vehicle_history_service_count", "="),
        ("vehicle_history_owner_count", "="),
        ("portal_urls", "ILIKE"),
    ],
    "default": [
        ("limit_count", 3),
        ("price_description", "not mentioned"),
        ("listing_min_price", 0),
        ("listing_max_price", 1000000000),
        ("listing_stock", None),
        ("listing_type", None),
        ("listing_mileage", None),
        ("vehicle_min_year", 0),
        ("vehicle_max_year", 4000),
        ("vehicle_make", None),
        ("vehicle_model", None),
        ("vehicle_trim", None),
        ("vehicle_style", None),
        ("vehicle_color_exterior", None),
        ("vehicle_color_interior", None),
        ("va_seller_name", None),
        ("va_seller_websites", None),
        ("va_seller_phones", None),
        ("va_seller_type", None),
        ("va_seller_address", None),
        ("va_seller_city", None),
        ("va_seller_state", None),
        ("va_seller_zip", None),
        ("va_seller_county", None),
        ("va_seller_country", None),
        ("va_seller_makes", None),
        ("va_seller_inventory_count_total", None),
        ("va_seller_inventory_count_new", None),
        ("va_seller_inventory_count_used", None),
        ("vdp_url", None),
        ("ymmt_id", None),
        ("listing_features", None),
        ("vehicle_title", None),
        ("vehicle_subtitle", None),
        ("vehicle_type", None),
        ("vehicle_truck_cab_style", None),
        ("vehicle_truck_bed_style", None),
        ("vehicle_engine", None),
        ("vehicle_engine_size", None),
        ("vehicle_engine_cylinders", None),
        ("vehicle_transmission", None),
        ("vehicle_transmission_type", None),
        ("vehicle_transmission_speed", None),
        ("vehicle_drivetrain", None),
        ("vehicle_doors", None),
        ("vehicle_fuel_type", None),
        ("vehicle_fuel_efficiency", None),
        ("vehicle_fuel_efficiency_highway", None),
        ("vehicle_fuel_efficiency_city", None),
        ("vehicle_history_description", None),
        ("vehicle_history_critical_count", None),
        ("vehicle_history_accident_count", None),
        ("vehicle_history_theft_count", None),
        ("vehicle_history_salvage_count", None),
        ("vehicle_history_service_count", None),
        ("vehicle_history_owner_count", None),
        ("portal_urls", None),
    ],
}

vehicle_description = [
    {"title": "Vehicle Title : ", "params": ["vehicle_title"]},
    {
        "title": "Model : ",
        "params": [
            "vehicle_year",
            "vehicle_make",
            "vehicle_model",
            "vehicle_trim",
            "vehicle_style",
        ],
    },
    {"title": "Type : ", "params": ["vehicle_doors", "vehicle_style"]},
    {"title": "Mileage : ", "params": ["listing_mileage"]},
    {
        "title": "History : ",
        "initial": "Clean",
        "type": "tail_array",
        "space": ",",
        "params": [
            {"arg": "vehicle_history_critical_count", "tail": "critical"},
            {"arg": "vehicle_history_accident_count", "tail": "accident"},
            {"arg": "vehicle_history_theft_count", "tail": "theft"},
            {"arg": "vehicle_history_salvage_count", "tail": "salvage"},
            {"arg": "vehicle_history_service_count", "tail": "service"},
            {"arg": "vehicle_history_owner_count", "tail": "previous owner(s)"},
        ],
    },
    {
        "title": "Color : ",
        "type": "tail_array",
        "params": [
            {"arg": "vehicle_color_exterior", "tail": "exterior"},
            {"arg": "vehicle_color_interior", "tail": "interior"},
        ],
    },
    {"title": "Engine : ", "params": ["vehicle_engine"]},
    {
        "title": "Fuel Efficiency: : ",
        "type": "tail_array",
        "space": ", ",
        "params": [
            {"arg": "vehicle_fuel_efficiency", "tail": "overall"},
            {"arg": "vehicle_fuel_highway", "tail": "highway"},
            {"arg": "vehicle_fuel_city", "tail": "city"},
        ],
    },
    {"title": "Price : $", "params": ["listing_price"]},
    {
        "title": "Seller : ",
        "params": [
            "va_seller_name",
            "va_seller_city",
            "va_seller_state",
            "va_seller_websites",
        ],
    },
    {"title": "Contact : ", "params": ["va_seller_phones"]},
    {
        "title": "Listing : ",
        "type": "tail_array",
        "params": [
            {"arg": "vdp_url", "tail": ""},
            {"arg": "listing_type", "tail": "("},
            {"arg": "date_min", "tail": "to"},
            {"arg": "date_max", "tail": ","},
            {"arg": "days_seen", "tail": " days seen)"},
        ],
    },
    {"title": "Features : ", "params": ["listing_features"]},
    {"title": "Description : ", "params": ["listing_description"]},
]
# "portal_urls": {
#     "type": "array",
#     "items": {"type": "string"},
#     "description": "URLs of the vehicle listing on various portals. (i.e. ['https://www.autotrader.com/cars-for-sale/vehicledetails.xhtml?listingId=674780315','https://www.carfax.com/vehicle/5N1AT2MV9GC810504',https://www.cargurus.com/Cars/inventorylisting/viewDetailsFilterViewInventoryListing.action#listing=351461535,'https://www.cars.com/vehicledetail/d4da7600-e9e3-47f0-8462-bd1ad41ef3d0/','https://www.edmunds.com/nissan/rogue/2016/vin/5N1AT2MV9GC810504/'])",
# },
